export const appSettings = {
    SET_LANGUAGE: "SET_LANGUAGE",
    TOGGLE_INFO: "TOGGLE_INFO",
    TOGGLE_MODAL: "TOGGLE_MODAL"
};

export const gameSettings = {
    SET_NUMBER_OF_PLAYERS: "SET_NUMBER_OF_PLAYERS",
    TOGGLE_TIMER: "TOGGLE_TIMER",
    UNLOCK_SCORE_FIELDS: "UNLOCK_SCORE_FIELDS"
};

export const session = {
    NUMBER_OF_PLAYERS_CHANGED: "NUMBER_OF_PLAYERS_CHANGED",
    SET_PLAYER_NAME: "SET_PLAYER_NAME",
    ADD_PLAYER_SCORE: "ADD_PLAYER_SCORE",
    EDIT_PLAYER_SCORE: "EDIT_PLAYER_SCORE",
    SET_TIME_ELAPSED: "SET_TIME_ELAPSED"
};